# Generated by Django 5.2 on 2025-04-21 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='Student',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_group',
            field=models.ForeignKey(help_text='Group of the student', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='Api.group'),
        ),
    ]
