# Generated by Django 5.2 on 2025-04-24 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='group',
            field=models.ForeignKey(default=None, help_text='Group for the course', null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.group'),
        ),
        migrations.AddField(
            model_name='course',
            name='module',
            field=models.CharField(default='DefaultModuleName', help_text='Module name', max_length=50),
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
