# Generated by Django 5.2 on 2025-04-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_course_group_course_module_delete_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='number',
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='DefaultGroupName', help_text='Group name', max_length=50),
        ),
    ]
