# Generated by Django 5.2 on 2025-04-29 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_remove_group_number_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='present_status',
            field=models.CharField(default='Abcent', help_text='The Attendance status', max_length=30),
        ),
    ]
