# Generated by Django 5.2 on 2025-04-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_alter_attendance_present_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date_time',
            field=models.DateTimeField(default=None, help_text='Date and time when the course starts', null=True),
        ),
    ]
