# Generated by Django 5.2 on 2025-05-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='present_status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Justified', 'Justified')], default='Absent', help_text='The attendance status', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'course', 'time')},
        ),
    ]
