# Generated by Django 5.2 on 2025-05-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_alter_attendance_present_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='present_status',
            field=models.CharField(default='Absent', help_text='The attendance status', max_length=30),
        ),
    ]
