# Generated by Django 5.2 on 2025-05-25 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='justification_detail',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='justification_file',
        ),
    ]
